config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  devise_for :users

  root 'top#home'
  #root 'books#index'

  resources :tops, only: [:home]
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  # Setup accessible (or protected) attributes for your model
  attr_accessor :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  enum status: {
    '所 持': 0, # possession
    '手放す': 1, # relinquish
  }

  mount_uploader :picture, PictureUploader

  def self.search(search)
    return Book.all unless search
    Book.where(['title LIKE ?', "%#{search}%"])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  # GET /books
  # GET /books.json
  def index
    @hon = Book.all
    @books = Kaminari.paginate_array(Book.search(params[:search])).page(params[:page])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy!
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:isbn, :title, :price, :publish, :published, :cd, :picture)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def home
    render :layout => nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>
  <br/>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <br/>
  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <br/>
  <div class="field">
    <%= form.label :publish %>
    <%= form.text_field :publish %>
  </div>
  <br/>
  <div class="field">
    <%= form.label :published %>
    <%= form.date_field(
            :published,
            value: (form.object.published || Time.now.strftime("%Y-%m-%d")),
        ) %>
  </div>
  <br/>
  <div class="field">
    <%= form.label :cd %>
    <%= form.check_box :cd %>
  </div>
  <br/>
  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :book_picture %>
  </div>
  <br/>
  <br/>
  <form>
    <div class="actions">
      <button type="submit" class="btn btn-primary">登録</button> <%= link_to '閲覧', @book, class: "btn btn-primary" %> <%= link_to '戻る', books_path, class: "btn btn-primary" %>
    </div>
  </form>
  <br/>
<% end %>

app/views/books/edit.html.erb
<div class="seep">
  <p>
  <h1>書籍編集</h1>
  <%= render 'form', book: @book %>
  <br/><br/>
  <br/><br/>
  </p>
</div>

<br/><br/>
<br/><br/>

app/views/books/index.html.erb
<div class="right">
  <%= link_to 'トップページ', root_path, class: "btn btn-primary" %> <%= link_to '新規追加', new_book_path, class: "btn btn-primary" %>  <%= link_to "CSV (SJIS)", books_path(format: :csv), class: "btn btn-primary" %> <%= link_to '管理画面', rails_admin_path, class: "btn btn-primary" %>
  <% if user_signed_in? %><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
  <% end %>
</div>

<div class="silver">
  <%= image_tag 'logo.png', :size => "105x105", skip_pipeline: true %>
</div>

<div class="pythonista">
  <%= image_tag 'python.png', :size => "105x105", skip_pipeline: true %>
</div>

<div class="pyruby">
  <%= image_tag 'python_ruby.png', :size => "105x105", skip_pipeline: true %>
</div>

<div class="zukkii">
  <%= image_tag 'hozuki.png', :size => "105x105", skip_pipeline: true %>
</div>

<div class="sponsor">
  <iframe src="https://github.com/sponsors/takkii/card" title="Sponsor takkii" height="225" width="600" style="border: 0;"></iframe>
</div>

<div class="shelf">
  <h1>Web Library System 「鬼灯」</h1>
</div>
<div class="timer">
  <h3><p id="RealtimeClockArea2"></p></h3>
</div>

<div class="left_search_icon">
<p>表示 : <%= @books.count %> 行 (データ数)</p>
</div>

<div class="left_search">
  <ul><%= form_tag(books_path, method: "get") do %>
    <i class="fab fa-searchengin"></i> : <%= text_field_tag :search, '', placeholder: '題名を入力' %>
    <%= submit_tag '検索', :name => nil %>
  <% end %>
</div>

<br />

<div class="left">
<h1>書籍</h1>
</div>

<br/>

<div class="left">
<table width="85%">

  <thead>

  <tr>
    <th>国際標準図書番号</th>
    <th>題 名</th>
    <th>
      <div align="center">価 格</div>
    </th>
    <th>著 者</th>
    <th>出 版 日</th>
    <th>写 真</th>
    <th>購 入</th>
    <th>状 態</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <div class="attach">
    <div class="list-group">
      <% @books.each do |book| %>
        <tr>
          <td>
            <% if book.isbn.present? %>
              <%= book.isbn %>
            <% else %>
              国際標準図書番号はありません
            <% end %>
          </td>
          <td>
            <% if book.title.present? %>
              <%= book.title %>
            <% else %>
              題名はありません
            <% end %>
          </td>
          <td>
            <div align="center">
              <% if book.price.present? %>
                <%= (book.price).to_s(:delimited) + "円" + " + 税(10%)" %>
              <% else %>
                価格 (¥)はありません
              <% end %>
            </div>
          </td>
          <td>
            <% if book.publish.present? %>
              <%= book.publish %>
            <% else %>
              著者はありません
            <% end %>
          </td>
          <td>
            <% if book.published.present? %>
              <%= book.published %>
            <% else %>
              出版日はありません
            <% end %>
          </td>
          <td>
            <% if book.picture.present? %>
              <%= book.picture %>
            <% else %>
              写真はありません
            <% end %>
          </td>
          <td>
            <% if book.cd.present? %>
              購入後
            <% else %>
              購入はありません
            <% end %>
          </td>
          <td>
            <% if book.status.present? %>
              <%= book.status %>
            <% else %>
              本はありません
            <% end %>
          </td>
          <td>
            <div align="right"><%= link_to '閲覧', book, class: "btn btn-primary" %></div>
          </td>
          <td>
            <div align="center"><%= link_to '編集', edit_book_path(book), class: "btn btn-primary" %></div>
          </td>
          <td>
            <div align="left"><%= link_to '削除', book, method: :delete, data: { confirm: '登録した書籍情報を削除しますか？' }, class: "btn btn-primary" %></div>
          </td>
        </tr>
      <% end %>
    </div>
  </div>
  </tbody>
</table>
</div>
</ul>
</div>
<br/>

<div class="left">
  <%= paginate @books %>
</div>

<br/>
<br/>
<br/>

app/views/books/new.html.erb
<div class="sleep">
  <p>
  <h1>新規追加</h1>
  <%= form_with(model: @book, local: true) do |form| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <br/>
    <div class="field">
      <%= form.label :isbn %>
      <%= form.text_field :isbn %>
    </div>
    <br/>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <br/>
    <div class="field">
      <%= form.label :price %>
      <%= form.number_field :price %>
    </div>
    <br/>
    <div class="field">
      <%= form.label :publish %>
      <%= form.text_field :publish %>
    </div>
    <br/>
    <div class="field">
      <%= form.label :published %>
      <%= form.date_field(
            :published,
            value: (form.object.published || Time.now.strftime("%Y-%m-%d")),
          ) %>
    </div>
    <br/>
    <div class="field">
      <%= form.label :cd %>
      <%= form.check_box :cd %>
    </div>
    <br/>
    <div class="field">
      <%= form.label :picture %>
      <%= form.file_field :picture, id: :book_picture %>
    </div>
    <br/>
    <form>
      <div class="actions">
        <button type="submit" class="btn btn-primary">登録</button> <%= link_to '戻る', books_path, class: "btn btn-primary" %>
      </div>
    </form>
    <br/>
  <% end %>
  </p>
</div>
<br/><br/><br/><br/>
<br/><br/><br/><br/>

app/views/books/search.html.erb
<div class="left">
	  <%= form_tag(books_path, method: "get") do %>
		<%= text_field_tag :search %>
		<%= submit_tag '検索', :name => nil %>
	  <% end %>

	  <ul><% @books.each do |book| %>
		<li>
		  <%= link_to book.title, book %>
		  <%= book.created_at %>
		  <%= book.status %>
		</li>
		<%= link_to "編集", edit_book_path(book) %>
		<%= link_to "削除", book, method: :delete %>
		<% end %>
	  </ul>
</div>

app/views/books/show.html.erb
<p>
<div class="leaf">
  <p id="notice"><%= notice %></p>
  <br/>
  <p>
    <strong>ISBN:</strong>
    <%= @book.isbn %>
  </p>
  <br/>
  <p>
    <strong>題名:</strong>
    <%= @book.title %>
  </p>
  <br/>
  <p>
    <strong>価格:</strong>
    <%= @book.price %>
  </p>
  <br/>
  <p>
    <strong>著者:</strong>
    <%= @book.publish %>
  </p>
  <br/>
  <p>
    <strong>出版日:</strong>
    <%= @book.published %>
  </p>
  <br/>
  <p>
    <strong>購入:</strong>
    <%= @book.cd %>
  </p>
  <br/>
  <p>
    <strong>写真:</strong>
    <%= image_tag(@book.picture.url) if @book.picture.present? %>
  </p>
  <br/>
  <%= link_to '編集', edit_book_path(@book), class: "btn btn-primary" %>
  <%= link_to '戻る', books_path, class: "btn btn-primary" %>
</div>
</p>
<br/><br/><br/><br/>
<br/><br/><br/><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Books Library</title>
  <%= favicon_link_tag 'hozukicon.ico', skip_pipeline: true %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  <%= csrf_meta_tag %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- %= javascript_pack_tag 'hello_typescript' % -->
</head>
<body>
<input type="checkbox" id="dark" name="dark">
<div class="switch-presentation">
  <label for="dark"><span class="day">&#9748;</span><span class="moon">&#9730;</span></label>
  <div class="content">
    <div class="scroll">
      <div id="container">
        <div class="attach">
          <div id="header">
            <div id="main-navigation">
              <ul class="wat-cf"></ul>
            </div>
          </div>
          <div id="wrapper" class="wat-cf">
            <div class="flash">
              <% flash.each do |type, message| -%>
                <div class="message <%= type %>">
                  <p>
                    <%= message %>
                  </p>
                </div>
              <% end -%>
            </div>
            <div id="main">
              <%= yield %>
              <div id="footer">
                <div class="block">
                  <div class="books">
                    <p> Copyright &copy; 2018 - <%= Time.now.year %> Takayuki, Kamiyama. </p>
                  </div>
                </div>
              </div>
            </div>
          <div class = "sns_logo">
            <a href="https://twitter.com/takkii"><i class="fab fa-twitter"></i></a>
            <a href="https://github.com/takkii/nyasocom2"><i class="fab fa-github"></i></a>
          </div>
          <div class="nyasocom2">
            <p><b> Not Yet Another Software design of Computer 2 powered by Ruby on Rails 6 </b></p>
          </div>
            <div id="sidebar">
              <%= yield :sidebar %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/top/home.html.erb
<!DOCTYPE html>
<html>
<head>
<%= favicon_link_tag 'hozukicon.ico', skip_pipeline: true %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
<%= csrf_meta_tag %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>

<div class="admin_buttons">
  <%= link_to('再読込', 'javascript:void(0);', onclick: "window.location.reload();", class: "btn btn-primary")  %> <%= link_to "図書室", books_url, class: "btn btn-primary" %>
</div>

<div class="body_wording">
<body>
<p class="typ">私の書斎、図書システムへようこそ！</p>
</body>
</div>
</html>